// <auto-generated />
using System;
using Microservice.VPDDataImport.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Microservice.VPDDataImport.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microservice.VPDDataImport.Domain.history", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("deleted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("file")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("file1")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("jsonresponse")
                        .HasColumnType("text");

                    b.Property<string>("jsonset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("namefile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("namefile1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("programsid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("state")
                        .HasColumnType("boolean");

                    b.Property<int>("uploads")
                        .HasColumnType("integer");

                    b.Property<string>("userlogin")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("id");

                    b.HasIndex("deleted");

                    b.HasIndex("id");

                    b.HasIndex("uploads");

                    b.ToTable("history");
                });
#pragma warning restore 612, 618
        }
    }
}
